### PR TITLE
Adds test configuration and some initial tests.

### PR DESCRIPTION
**Pull request by jakeharding**
I am interested in maintaining the repo if you are still looking to off load it.

### CODE REVIEW

**Comment by george-mengelberg** [comment]
Sure....let me figure out how to pass it to you.

**Comment by jakeharding** [comment]
I believe it's in Settings, towards the bottom.

**Comment by george-mengelberg** [comment]
Another guy is the owner and I don't have the ability to transfer it.  I
will work with him to git it to you. :~)

**Comment by jakeharding** [comment]
Cool.  Thanks!

**Comment by Fandekasp** [comment]
hi @jakeharding can you delete your copy of django-jasmine ? I cannot transfer the repo due to "jakeharding/django-jasmine already exists".

**Comment by jakeharding** [comment]
I changed the name so let's see if that works.

**Comment by Fandekasp** [comment]
@jakeharding sorry about that, github is being very picky today. Now getting `jakeharding already has a repository in the Fandekasp/django-jasmine network`.

I suggest you to remove your fork from github, then sync your computer local version with the upstream one after I transfer ownership

**Comment by jakeharding** [comment]
@Fandekasp Yep. Done.

**Comment by Fandekasp** [comment]
Done. Thank you for taking over @jakeharding !

**Pull request closed without merging**
